import Head from 'next/head'
import styles from '@/styles/Home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>WD Baas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/crypto.png" />
      </Head>
      <main className={styles.main}>
        <div style={{ padding: 100 }}>
          <section>
            <span>Address: {}</span>
          </section>
        </div>
      </main>
    </>
  )
}
