import Head from 'next/head'
import styles from '@/styles/Layout.module.scss'
import { Col, Row } from 'antd'
import { Card } from 'antd';
import Earn from '@/components/Earn'
import { GetServerSideProps } from 'next';
import { generateRandomWalletAddress } from '@/packages/lib/address';
import prisma from '@/packages/lib/prisma';
import { Address } from '@prisma/client';
import Wallet from '@/components/Wallet';
import AddressList from '@/components/Address';

export const getServerSideProps: GetServerSideProps = async () => {
  const address = await prisma.address.findMany()
  const serializedData = JSON.parse(JSON.stringify(address, (key, value) => {
    if (key === 'createTime') {
      return new Date(value).toISOString();
    }
    return value;
  }));
  console.log(serializedData)
  return {
    props: { address: serializedData },
  };
};

export default function Home(props: { address: Address[] }) {
  console.log(props.address)
  return (
    <>
      <Head>
        <title>WD Baas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/crypto.png" />
      </Head>
      <main className={styles.main}>
        <Row gutter={16}>
          <Col span={12}>
            <Card title="Money" bordered={false}>
              <Earn />
            </Card>
          </Col>
          <Col span={12}>
            <Card title="Wallet" bordered={false}>
              <Wallet />
            </Card>
          </Col>
          <Col span={12}>
            <Card title="Address" bordered={false}>
              <AddressList
                list={props.address.map(item => ({ address: item.publicKey, time: item.createTime }))}
              />
            </Card>
          </Col>
        </Row>
      </main>
    </>
  )
}
